name: Feature Request
description: Suggest an idea for DeepFilterNet
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving DeepFilterNet!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Which component would this affect?
      multiple: true
      options:
        - DeepFilterNet (Python)
        - deep-filter (Rust binary)
        - libDF (Rust library)
        - LADSPA plugin
        - Demo application
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
