#!/usr/bin/env python3
"""Generate VLC and MPV playlists from enhancement manifest.

This script reads the enhancement manifest created by enhance_video_audio.py
and generates player-specific playlists and launch scripts for seamless
playback with switchable original/enhanced audio tracks.

Supports:
- VLC M3U playlists with EXTVLCOPT:input-slave directives
- MPV shell scripts with --audio-file options
- Optional audio mixing for pre-mixed tracks

Usage:
    # Generate VLC playlist
    python generate_playlists.py \\
        --manifest-path /path/to/enhancement_manifest.json \\
        --output-dir /path/to/playlists \\
        --player vlc

    # Generate both VLC and MPV playlists
    python generate_playlists.py \\
        --manifest-path enhancement_manifest.json \\
        --player both

    # Generate with custom name
    python generate_playlists.py \\
        --manifest enhancement_manifest.json \\
        --playlist-name my_enhanced_videos
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
from pathlib import Path
from typing import Any


def generate_vlc_playlist(
    manifest: dict[str, Any],
    output_path: Path,
    use_relative_paths: bool = False,
) -> None:
    """Generate M3U playlist for VLC with sidecar audio support.

    Args:
        manifest: Enhancement manifest dict
        output_path: Path to output M3U file
        use_relative_paths: Use relative paths instead of absolute
    """
    lines = ["#EXTM3U"]

    for entry in manifest["videos"]:
        video_path = entry.get("video_path_relative" if use_relative_paths else "video_path")
        audio_path = entry.get("enhanced_audio_path_relative" if use_relative_paths else "enhanced_audio_path")

        # Convert to file:// URLs for VLC (absolute paths only)
        if not use_relative_paths:
            video_url = f"file://{video_path}"
            audio_url = f"file://{audio_path}"
        else:
            video_url = video_path
            audio_url = audio_path

        # Add entry with sidecar audio directive
        video_name = Path(video_path).name
        lines.append(f"#EXTINF:-1,{video_name}")
        lines.append(f"#EXTVLCOPT:input-slave={audio_url}")
        lines.append(video_url)

    # Write playlist
    output_path.write_text("\n".join(lines) + "\n")
    print(f"✅ VLC playlist created: {output_path}")
    print(f"   Videos: {len(manifest['videos'])}")
    print(f"   Usage: Open in VLC → Audio → Audio Track → Select enhanced track")


def generate_mpv_playlist(
    manifest: dict[str, Any],
    output_path: Path,
    use_relative_paths: bool = False,
) -> None:
    """Generate MPV-compatible playlist file.

    Args:
        manifest: Enhancement manifest dict
        output_path: Path to output playlist file
        use_relative_paths: Use relative paths instead of absolute
    """
    lines = []

    for entry in manifest["videos"]:
        video_path = entry.get("video_path_relative" if use_relative_paths else "video_path")
        audio_path = entry.get("enhanced_audio_path_relative" if use_relative_paths else "enhanced_audio_path")

        # MPV playlist format: video path with audio file comment
        lines.append(video_path)
        lines.append(f"#AUDIOFILE:{audio_path}")

    # Write playlist
    output_path.write_text("\n".join(lines) + "\n")
    print(f"✅ MPV playlist created: {output_path}")
    print(f"   Videos: {len(manifest['videos'])}")
    print(f"   Note: MPV #AUDIOFILE directive support may vary by version")


def generate_mpv_script(
    manifest: dict[str, Any],
    output_path: Path,
    use_relative_paths: bool = False,
) -> None:
    """Generate bash script to launch MPV with --audio-file option.

    Args:
        manifest: Enhancement manifest dict
        output_path: Path to output shell script
        use_relative_paths: Use relative paths instead of absolute
    """
    lines = [
        "#!/usr/bin/env bash",
        "#",
        "# MPV playback script for enhanced audio",
        "# Generated by generate_playlists.py",
        "#",
        "# Usage: ./play_enhanced_mpv.sh [video_index]",
        "#   video_index: 1-based index (default: play all)",
        "",
        "set -euo pipefail",
        "",
    ]

    # Array of video/audio pairs
    lines.append("# Video and audio file pairs")
    lines.append("declare -a VIDEOS=(")
    for entry in manifest["videos"]:
        video_path = entry.get("video_path_relative" if use_relative_paths else "video_path")
        lines.append(f"  {shlex.quote(video_path)}")
    lines.append(")")
    lines.append("")

    lines.append("declare -a AUDIOS=(")
    for entry in manifest["videos"]:
        audio_path = entry.get("enhanced_audio_path_relative" if use_relative_paths else "enhanced_audio_path")
        lines.append(f"  {shlex.quote(audio_path)}")
    lines.append(")")
    lines.append("")

    # Playback logic
    lines.extend(
        [
            "# Determine which videos to play",
            "if [[ $# -eq 1 ]]; then",
            "  INDEX=$(( $1 - 1 ))",
            "  if [[ $INDEX -lt 0 || $INDEX -ge ${#VIDEOS[@]} ]]; then",
            '    echo "❌ Invalid video index: $1 (valid range: 1-${#VIDEOS[@]})"',
            "    exit 1",
            "  fi",
            '  echo "▶️  Playing video $1 of ${#VIDEOS[@]}"',
            '  mpv "${VIDEOS[$INDEX]}" --audio-file="${AUDIOS[$INDEX]}"',
            "else",
            '  echo "▶️  Playing all ${#VIDEOS[@]} videos"',
            '  for i in "${!VIDEOS[@]}"; do',
            '    echo ""',
            '    echo "Video $(( i + 1 )) of ${#VIDEOS[@]}: ${VIDEOS[$i]}"',
            '    mpv "${VIDEOS[$i]}" --audio-file="${AUDIOS[$i]}"',
            "  done",
            "fi",
            "",
            'echo ""',
            'echo "✅ Playback complete"',
        ]
    )

    # Write script
    output_path.write_text("\n".join(lines) + "\n")
    output_path.chmod(0o755)  # Make executable

    print(f"✅ MPV script created: {output_path}")
    print(f"   Videos: {len(manifest['videos'])}")
    print(f"   Usage: {output_path} [video_index]")
    print(f"   Press # during playback to switch audio tracks")


def generate_mixed_audio(
    manifest: dict[str, Any],
    mix_ratios: list[tuple[int, int]],
    output_dir: Path,
) -> None:
    """Generate pre-mixed audio files at specified ratios.

    Args:
        manifest: Enhancement manifest dict
        mix_ratios: List of (original%, enhanced%) tuples, e.g., [(50,50), (70,30)]
        output_dir: Directory to save mixed audio files
    """
    print("\n" + "=" * 60)
    print("Generating Mixed Audio Files")
    print("=" * 60)

    output_dir.mkdir(parents=True, exist_ok=True)
    total = len(manifest["videos"]) * len(mix_ratios)
    processed = 0

    for entry in manifest["videos"]:
        video_path = Path(entry["video_path"])
        enhanced_audio_path = Path(entry["enhanced_audio_path"])

        # Extract original audio if not already done
        original_audio = output_dir / f"{video_path.stem}_original.wav"
        if not original_audio.exists():
            print(f"\nExtracting original audio: {video_path.name}")
            cmd = [
                "ffmpeg",
                "-i",
                str(video_path),
                "-vn",
                "-acodec",
                "pcm_s16le",
                "-ar",
                "48000",
                "-y",
                str(original_audio),
            ]
            result = subprocess.run(cmd, capture_output=True)
            if result.returncode != 0:
                print(f"  ⚠️  Failed to extract original audio: {result.stderr[-200:]}")
                continue

        # Convert enhanced audio to WAV if it's not already
        enhanced_wav = output_dir / f"{video_path.stem}_enhanced.wav"
        if not enhanced_wav.exists():
            if enhanced_audio_path.suffix.lower() in [".m4a", ".aac"]:
                print(f"  Converting enhanced audio to WAV...")
                cmd = [
                    "ffmpeg",
                    "-i",
                    str(enhanced_audio_path),
                    "-acodec",
                    "pcm_s16le",
                    "-ar",
                    "48000",
                    "-y",
                    str(enhanced_wav),
                ]
                result = subprocess.run(cmd, capture_output=True)
                if result.returncode != 0:
                    print(f"  ⚠️  Failed to convert enhanced audio: {result.stderr[-200:]}")
                    continue
            else:
                enhanced_wav = enhanced_audio_path

        # Generate mixed versions
        for orig_pct, enh_pct in mix_ratios:
            mixed_name = f"{video_path.stem}_mixed_{orig_pct}-{enh_pct}.m4a"
            mixed_path = output_dir / mixed_name

            if mixed_path.exists():
                processed += 1
                continue

            print(f"  Mixing {orig_pct}/{enh_pct}: {mixed_name}")

            # Calculate weights (0.0-1.0 scale)
            orig_weight = orig_pct / 100.0
            enh_weight = enh_pct / 100.0

            cmd = [
                "ffmpeg",
                "-i",
                str(original_audio),
                "-i",
                str(enhanced_wav),
                "-filter_complex",
                f"[0:a][1:a]amix=inputs=2:duration=longest:weights={orig_weight} {enh_weight}",
                "-c:a",
                "aac",
                "-b:a",
                "192k",
                "-y",
                str(mixed_path),
            ]

            result = subprocess.run(cmd, capture_output=True)
            if result.returncode == 0:
                processed += 1
                print(f"  ✅ Created: {mixed_path.name}")
            else:
                print(f"  ⚠️  Failed: {result.stderr[-200:]}")

    print(f"\n✅ Mixed audio generation complete: {processed}/{total} successful")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate VLC/MPV playlists from enhancement manifest",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    parser.add_argument(
        "--manifest-path",
        type=Path,
        required=True,
        help="Path to enhancement manifest JSON file",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Output directory for playlists (default: same as manifest)",
    )
    parser.add_argument(
        "--player",
        choices=["vlc", "mpv", "both"],
        default="both",
        help="Generate playlists for which player (default: both)",
    )
    parser.add_argument(
        "--playlist-name",
        default="enhanced_audio_playlist",
        help="Base name for generated playlists (default: enhanced_audio_playlist)",
    )
    parser.add_argument(
        "--relative-paths",
        action="store_true",
        help="Use relative paths instead of absolute (may not work with all players)",
    )
    parser.add_argument(
        "--generate-mixed",
        action="store_true",
        help="Generate pre-mixed audio files (original + enhanced)",
    )
    parser.add_argument(
        "--mix-ratios",
        nargs="+",
        default=["50:50", "70:30"],
        help="Mix ratios as original:enhanced percentages (default: 50:50 70:30)",
    )

    args = parser.parse_args()

    # Validate manifest exists
    if not args.manifest_path.exists():
        print(f"❌ Error: Manifest not found: {args.manifest_path}")
        return 1

    # Default output directory
    if args.output_dir is None:
        args.output_dir = args.manifest_path.parent

    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Load manifest
    print("=" * 60)
    print("Playlist Generation")
    print("=" * 60)
    print(f"Manifest: {args.manifest_path}")
    print(f"Output: {args.output_dir}")
    print()

    try:
        with open(args.manifest_path) as f:
            manifest = json.load(f)
    except Exception as e:
        print(f"❌ Error loading manifest: {e}")
        return 1

    if "videos" not in manifest or not manifest["videos"]:
        print("❌ Error: Manifest contains no videos")
        return 1

    # Generate VLC playlist
    if args.player in ["vlc", "both"]:
        vlc_path = args.output_dir / f"{args.playlist_name}.m3u"
        generate_vlc_playlist(manifest, vlc_path, args.relative_paths)

    # Generate MPV playlist/script
    if args.player in ["mpv", "both"]:
        mpv_playlist_path = args.output_dir / f"{args.playlist_name}_mpv.txt"
        mpv_script_path = args.output_dir / f"play_{args.playlist_name}_mpv.sh"

        generate_mpv_playlist(manifest, mpv_playlist_path, args.relative_paths)
        print()
        generate_mpv_script(manifest, mpv_script_path, args.relative_paths)

    # Generate mixed audio if requested
    if args.generate_mixed:
        # Parse mix ratios
        mix_ratios = []
        for ratio_str in args.mix_ratios:
            try:
                orig, enh = ratio_str.split(":")
                mix_ratios.append((int(orig), int(enh)))
            except Exception:
                print(f"⚠️  Invalid mix ratio format: {ratio_str} (expected XX:YY)")
                continue

        if mix_ratios:
            mixed_dir = args.output_dir / "mixed_audio"
            generate_mixed_audio(manifest, mix_ratios, mixed_dir)

    print("\n" + "=" * 60)
    print("✅ Playlist generation complete")
    print("=" * 60)

    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
